name: Feature Request
description: 新機能の提案や既存機能の改善案を記入
labels: enhancement

body:
  - type: textarea
    id: task_overview
    attributes:
      label: タスクの内容
      description: 何を行うのか簡潔に記載

  - type: textarea
    id: reason
    attributes:
      label: 背景・目的
      description: タスクが必要な理由を記載
